version: '3.4'

services:
  messagingservice:
    image: messagingservice:dev
    container_name: MessagingService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MessagingService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_messagingservice$
    volumes:
      - C:\Users\kerim\source\repos\KerimCanIslamoglu\MessagingService\MessagingService:/app
      - C:\Users\kerim\source\repos\KerimCanIslamoglu\MessagingService:/src
      - C:\Users\kerim\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_messagingservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_messagingservice$ \"/app/bin/Debug/netcoreapp3.1/MessagingService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true